# SPDX-FileCopyrightText: 2024 dffdff2423 <dffdff2423@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-only

name: Check Reuse Compliance

on: [ push ]

jobs:
  check-reuse-compliance:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install and lint project with reuse
      run: pipx run reuse lint
